const authStatus=document.querySelector('[data-auth-status]');
const signupForm=document.querySelector('[data-signup-form]');
const loginForm=document.querySelector('[data-login-form]');
const logoutButton=document.querySelector('[data-logout]');
const profileForm=document.querySelector('[data-profile-form]');
const garageList=document.querySelector('[data-garage-list]');
const profileSummary=document.querySelector('[data-profile-summary]');

function setStatus(message,type=''){if(!authStatus)return;authStatus.textContent=message;authStatus.className=type;}
function friendlyError(error,context='general'){if(typeof window.hotFlashFriendlyError==='function')return window.hotFlashFriendlyError(error,context);console.error(`[Hot Flash ${context} error]`,error);return 'Something went wrong. Please try again.';}
function slugify(value){return String(value||'').toLowerCase().trim().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,32);}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function safeCssUrl(value){return String(value||'').replace(/["'()\\\n\r]/g,'');}
function requestedReturnTo(){const raw=new URLSearchParams(location.search).get('returnTo');if(!raw)return 'dashboard.html';try{const url=new URL(raw,location.origin);if(url.origin===location.origin)return `${url.pathname}${url.search}${url.hash}`;}catch(_){}return 'dashboard.html';}
function installPasswordToggles(){document.querySelectorAll('input[type="password"]').forEach(input=>{if(input.closest('.password-field'))return;const wrapper=document.createElement('div');wrapper.className='password-field';const button=document.createElement('button');button.type='button';button.className='password-toggle';button.setAttribute('aria-label','Show password');button.textContent='Show';input.parentNode.insertBefore(wrapper,input);wrapper.append(input,button);button.addEventListener('click',()=>{const hidden=input.type==='password';input.type=hidden?'text':'password';button.textContent=hidden?'Hide':'Show';button.setAttribute('aria-label',hidden?'Hide password':'Show password');});});}
installPasswordToggles();

async function getSession(){if(typeof window.hotFlashGetStableSession==='function')return window.hotFlashGetStableSession();const{data,error}=await hotflashSupabase.auth.getSession();if(error)throw error;return data.session;}
async function requireSession(){const session=await getSession();if(!session){const destination=`login.html?returnTo=${encodeURIComponent(location.pathname+location.search)}`;location.replace(destination);return null;}return session;}

async function loadGarage(userId){if(!garageList)return;garageList.setAttribute('aria-busy','true');garageList.innerHTML='<article class="post-card"><strong>Loading garage…</strong></article>';const{data,error}=await hotflashSupabase.from('vehicles').select('*').eq('owner_id',userId).order('created_at',{ascending:false});garageList.removeAttribute('aria-busy');if(error){console.error('[Hot Flash garage load error]',error);garageList.innerHTML='<article class="post-card"><strong>Garage unavailable</strong><p class="small-muted">We could not load your garage right now. Refresh and try again.</p></article>';return;}if(!data?.length){garageList.innerHTML='<article class="post-card"><strong>Your garage is ready for its first vehicle.</strong><p class="small-muted">Add a ride using the form and its public profile will be created automatically.</p></article>';return;}garageList.innerHTML=data.map(vehicle=>{const nickname=escapeHtml(vehicle.nickname||'Untitled vehicle');const summary=[vehicle.year,vehicle.make,vehicle.model].filter(Boolean).map(escapeHtml).join(' ');const detail=escapeHtml(vehicle.powertrain||vehicle.engine||vehicle.build_summary||'Build details coming soon');const id=escapeHtml(vehicle.hotflash_id||'Hot Flash build');const style=vehicle.cover_photo?` style="background-image:linear-gradient(0deg,rgba(5,6,7,.58),rgba(5,6,7,.08)),url(&quot;${safeCssUrl(vehicle.cover_photo)}&quot;)"`:'';return `<article class="vehicle-card vehicle-card-live" data-vehicle-id="${escapeHtml(vehicle.id)}"><div class="vehicle-art ${vehicle.cover_photo?'has-cover':''}"${style}></div><div class="vehicle-body"><p class="eyebrow">${id}</p><h2>${nickname}</h2><p class="vehicle-meta">${summary||'Vehicle details not added yet'}</p><p class="small-muted">${detail}</p></div></article>`;}).join('');}

async function loadDashboard(){const session=await requireSession();if(!session)return;const user=session.user;const{data:profile,error}=await hotflashSupabase.from('profiles').select('*').eq('id',user.id).maybeSingle();if(error)throw error;if(profileSummary){profileSummary.innerHTML=profile?`<strong>${escapeHtml(profile.display_name||profile.username||'Hot Flash member')}</strong><span>@${escapeHtml(profile.username||'member')}</span>`:'<strong>Welcome to Hot Flash</strong><span>Finish your profile below.</span>';}if(profileForm&&profile){profileForm.display_name.value=profile.display_name||'';profileForm.username.value=profile.username||'';profileForm.bio.value=profile.bio||'';if(profileForm.music_autoplay)profileForm.music_autoplay.checked=Boolean(profile.music_autoplay);}await loadGarage(user.id);setStatus('Garage ready.','success');}

signupForm?.addEventListener('submit',async event=>{event.preventDefault();if(!signupForm.reportValidity())return;const submit=signupForm.querySelector('button[type="submit"]');if(submit?.disabled)return;submit.disabled=true;setStatus('Creating your Hot Flash account…');const form=new FormData(signupForm);const email=String(form.get('email')||'').trim().toLowerCase();const password=String(form.get('password')||'');const username=slugify(form.get('username'));const displayName=String(form.get('display_name')||'').trim();if(username.length<3){setStatus('Username must be at least 3 characters.','error');submit.disabled=false;return;}try{const{data,error}=await hotflashSupabase.auth.signUp({email,password,options:{data:{username,display_name:displayName}}});if(error)throw error;if(!data.user)throw new Error('Account creation returned no user.');const{error:profileError}=await hotflashSupabase.from('profiles').upsert({id:data.user.id,username,display_name:displayName,email,bio:''});if(profileError)console.warn('[Hot Flash profile setup]',profileError);signupForm.reset();setStatus(data.session?'Account created! Opening your garage…':'Account created! Check your email to confirm it, then sign in.','success');if(data.session)setTimeout(()=>location.assign('dashboard.html'),700);}catch(error){setStatus(friendlyError(error,'signup'),'error');}finally{submit.disabled=false;}});

loginForm?.addEventListener('submit',async event=>{event.preventDefault();if(!loginForm.reportValidity())return;const submit=loginForm.querySelector('button[type="submit"]');if(submit?.disabled)return;submit.disabled=true;setStatus('Logging in…');const form=new FormData(loginForm);try{const{error}=await hotflashSupabase.auth.signInWithPassword({email:String(form.get('email')||'').trim().toLowerCase(),password:String(form.get('password')||'')});if(error)throw error;location.replace(requestedReturnTo());}catch(error){setStatus(friendlyError(error,'login'),'error');submit.disabled=false;}});

logoutButton?.addEventListener('click',async()=>{logoutButton.disabled=true;setStatus('Logging out…');try{await hotflashSupabase.auth.signOut();location.replace('login.html');}catch(error){logoutButton.disabled=false;setStatus(friendlyError(error,'logout'),'error');}});

profileForm?.addEventListener('submit',async event=>{event.preventDefault();if(!profileForm.reportValidity())return;const session=await requireSession();if(!session)return;const submit=profileForm.querySelector('button[type="submit"]');if(submit?.disabled)return;submit.disabled=true;setStatus('Saving profile…');const form=new FormData(profileForm);const username=slugify(form.get('username'));if(username.length<3){setStatus('Username must be at least 3 characters.','error');submit.disabled=false;return;}const payload={id:session.user.id,email:session.user.email,username,display_name:String(form.get('display_name')||'').trim(),bio:String(form.get('bio')||'').trim(),music_autoplay:Boolean(form.get('music_autoplay'))};const{error}=await hotflashSupabase.from('profiles').upsert(payload);submit.disabled=false;if(error){setStatus(friendlyError(error,'profile'),'error');return;}setStatus('Profile saved.','success');await loadDashboard();});

if(document.body.dataset.page==='dashboard')loadDashboard().catch(error=>{console.error('[Hot Flash dashboard error]',error);setStatus('We could not load your dashboard. Refresh and try again.','error');});
