function canonicalVehicleUrl(vehicle){const key=vehicle.hotflash_id||vehicle.id;return `https://hotflash.app/vehicle.html?hf=${encodeURIComponent(key)}`;}
function buildQr(target,text,size=280){if(!target||typeof QRCode==='undefined')return;target.innerHTML='';new QRCode(target,{text,width:size,height:size,colorDark:'#050607',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.H});}
function flashTagFilename(vehicle){const safe=(vehicle.hotflash_id||vehicle.nickname||'hotflash-vehicle').replace(/[^a-z0-9-_]/gi,'-');return `${safe}-flashtag.png`;}
function downloadQr(target,vehicle){const canvas=target?.querySelector('canvas');const image=target?.querySelector('img');const href=canvas?.toDataURL('image/png')||image?.src;if(!href)return;const link=document.createElement('a');link.href=href;link.download=flashTagFilename(vehicle);link.click();}
async function shareVehicle(vehicle,url,status){try{if(navigator.share){await navigator.share({title:`${vehicle.nickname} on Hot Flash`,text:`Check out ${vehicle.nickname} on Hot Flash.`,url});if(status)status.textContent='Shared.';}else{await navigator.clipboard.writeText(url);if(status)status.textContent='Link copied.';}}catch(error){if(error.name!=='AbortError'&&status)status.textContent='Could not share this link.';}}
window.renderFlashTag=function(vehicle){const card=document.querySelector('[data-flashtag-card]');const qr=document.querySelector('[data-flashtag-qr]');if(!card||!qr||!vehicle)return;const url=canonicalVehicleUrl(vehicle);const id=vehicle.hotflash_id||'Hot Flash vehicle';card.hidden=false;card.classList.toggle('founder-flashtag',['HF-000001','HF-000002'].includes(id));document.querySelector('[data-flashtag-id]').textContent=id;document.querySelector('[data-flashtag-name]').textContent=vehicle.nickname||'Vehicle FlashTag';document.querySelector('[data-flashtag-url]').textContent=url;buildQr(qr,url,280);document.querySelector('[data-flashtag-download]')?.addEventListener('click',()=>downloadQr(qr,vehicle));document.querySelector('[data-flashtag-copy]')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(url);document.querySelector('[data-flashtag-status]').textContent='Link copied.';});document.querySelector('[data-flashtag-share]')?.addEventListener('click',()=>shareVehicle(vehicle,url,document.querySelector('[data-flashtag-status]')));const printLink=document.querySelector('[data-flashtag-print]');if(printLink)printLink.href=`flashtag.html?hf=${encodeURIComponent(id)}`;};
async function findVehicle(ref){let query=hotflashSupabase.from('vehicles').select('*');query=ref.startsWith('HF-')?query.eq('hotflash_id',ref):query.eq('id',ref);return query.maybeSingle();}
async function loadVehicleFlashTag(){if(document.body.dataset.page!=='vehicle')return;const params=new URLSearchParams(location.search);const ref=params.get('hf')||params.get('id');if(!ref)return;const{data:vehicle}=await findVehicle(ref);if(vehicle)window.renderFlashTag(vehicle);}
async function loadPrintableFlashTag(){if(document.body.dataset.page!=='flashtag')return;const ref=new URLSearchParams(location.search).get('hf');const status=document.querySelector('[data-print-status]');if(!ref){status.textContent='No vehicle selected.';return;}const{data:vehicle,error}=await findVehicle(ref);if(error||!vehicle){status.textContent=error?.message||'Vehicle not found.';return;}const url=canonicalVehicleUrl(vehicle);document.title=`${vehicle.nickname} FlashTag | Hot Flash`;document.querySelector('[data-print-id]').textContent=vehicle.hotflash_id||'Hot Flash';document.querySelector('[data-print-name]').textContent=vehicle.nickname;document.querySelector('[data-print-meta]').textContent=[vehicle.year,vehicle.make,vehicle.model].filter(Boolean).join(' ');document.querySelector('[data-print-url]').textContent=url;const qr=document.querySelector('[data-print-qr]');buildQr(qr,url,360);document.querySelector('[data-print-download]')?.addEventListener('click',()=>downloadQr(qr,vehicle));document.querySelector('[data-print-button]')?.addEventListener('click',()=>window.print());status.textContent='';}
document.addEventListener('DOMContentLoaded',()=>{loadVehicleFlashTag();loadPrintableFlashTag();});