function canonicalVehicleUrl(vehicle){const key=vehicle.hotflash_id||vehicle.id;return `https://hotflash.app/vehicle.html?hf=${encodeURIComponent(key)}`;}
function founderNumber(vehicle){const match=/^HF-(\d{6})$/.exec(vehicle?.hotflash_id||'');if(!match)return null;const n=Number(match[1]);return n>=1&&n<=100?n:null;}
function safeFilePart(value){return String(value||'hotflash').replace(/[^a-z0-9-_]+/gi,'-').replace(/^-+|-+$/g,'').toLowerCase();}
function flashTagFilename(vehicle,founder=false){return `${safeFilePart(vehicle.hotflash_id||vehicle.nickname)}-${founder?'founder-sticker':'flashtag'}.png`;}
function buildQr(target,text,size=280){if(!target||typeof QRCode==='undefined')return;target.innerHTML='';new QRCode(target,{text,width:size,height:size,colorDark:'#050607',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.H});}
function qrCanvas(text,size=700){const holder=document.createElement('div');holder.style.cssText='position:fixed;left:-9999px;top:-9999px';document.body.appendChild(holder);buildQr(holder,text,size);const source=holder.querySelector('canvas')||holder.querySelector('img');return new Promise((resolve,reject)=>{if(source?.tagName==='CANVAS'){const copy=document.createElement('canvas');copy.width=source.width;copy.height=source.height;copy.getContext('2d').drawImage(source,0,0);holder.remove();resolve(copy);}else if(source){source.onload=()=>{const copy=document.createElement('canvas');copy.width=size;copy.height=size;copy.getContext('2d').drawImage(source,0,0,size,size);holder.remove();resolve(copy);};source.onerror=()=>{holder.remove();reject(new Error('QR code could not be rendered.'));}}else{holder.remove();reject(new Error('QR library is unavailable.'));}});}
function fitText(ctx,text,maxWidth,startSize,minSize=28){let size=startSize;while(size>minSize){ctx.font=`900 ${size}px Inter,Arial,sans-serif`;if(ctx.measureText(text).width<=maxWidth)break;size-=2;}return size;}
function roundedRect(ctx,x,y,w,h,r){const radius=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+radius,y);ctx.arcTo(x+w,y,x+w,y+h,radius);ctx.arcTo(x+w,y+h,x,y+h,radius);ctx.arcTo(x,y+h,x,y,radius);ctx.arcTo(x,y,x+w,y,radius);ctx.closePath();}
function metallicGradient(ctx,x1,y1,x2,y2){const g=ctx.createLinearGradient(x1,y1,x2,y2);g.addColorStop(0,'#fff7ff');g.addColorStop(.13,'#b9ffff');g.addColorStop(.27,'#fff0a8');g.addColorStop(.42,'#e4bbff');g.addColorStop(.58,'#9fffea');g.addColorStop(.72,'#fff3bf');g.addColorStop(.86,'#b5c8ff');g.addColorStop(1,'#ffffff');return g;}
function neonGradient(ctx,x1,y1,x2,y2){const g=ctx.createLinearGradient(x1,y1,x2,y2);g.addColorStop(0,'#b6ff00');g.addColorStop(.5,'#82ff00');g.addColorStop(1,'#8b2eff');return g;}
function drawHexTexture(ctx,size){ctx.save();ctx.globalAlpha=.16;ctx.strokeStyle='#6f7782';ctx.lineWidth=2;const r=18;const h=Math.sqrt(3)*r;for(let row=-2;row<size/h+2;row++){for(let col=-2;col<size/(r*3)+2;col++){const cx=col*r*3+(row%2?1.5*r:0),cy=row*h;ctx.beginPath();for(let i=0;i<6;i++){const a=Math.PI/3*i;const x=cx+r*Math.cos(a),y=cy+r*Math.sin(a);i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.closePath();ctx.stroke();}}ctx.restore();}
async function buildFounderSticker(vehicle,profile={}){const S=1600,c=document.createElement('canvas'),ctx=c.getContext('2d');c.width=c.height=S;const n=founderNumber(vehicle);const url=canonicalVehicleUrl(vehicle);const owner=profile.display_name||profile.username||'Hot Flash Founder';const handle=profile.username?`@${profile.username}`:owner;const nickname=vehicle.nickname||'Founder Build';
ctx.fillStyle='#000';ctx.fillRect(0,0,S,S);ctx.save();ctx.beginPath();ctx.arc(S/2,S/2,770,0,Math.PI*2);ctx.clip();const bg=ctx.createRadialGradient(800,580,100,800,800,900);bg.addColorStop(0,'#1b2025');bg.addColorStop(.58,'#080a0c');bg.addColorStop(1,'#020303');ctx.fillStyle=bg;ctx.fillRect(0,0,S,S);drawHexTexture(ctx,S);ctx.restore();
ctx.save();ctx.lineWidth=28;ctx.strokeStyle=metallicGradient(ctx,80,60,1520,1540);ctx.shadowColor='#8b2eff';ctx.shadowBlur=24;ctx.beginPath();ctx.arc(800,800,770,0,Math.PI*2);ctx.stroke();ctx.lineWidth=8;ctx.strokeStyle='#84ff00';ctx.beginPath();ctx.arc(800,800,738,0,Math.PI*2);ctx.stroke();ctx.restore();
ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='900 italic 138px Inter,Arial,sans-serif';ctx.shadowColor='#8b2eff';ctx.shadowBlur=18;ctx.fillText('HOT FLASH',800,270);ctx.shadowBlur=0;ctx.fillStyle='#f5f5f5';ctx.font='900 39px Inter,Arial,sans-serif';ctx.fillText('TUNING.  COMMUNITY.  PASSION.',800,326);ctx.fillStyle='#84ff00';ctx.fillRect(440,346,720,8);
ctx.textAlign='left';ctx.fillStyle='#f4c74d';ctx.font='900 64px Inter,Arial,sans-serif';ctx.fillText('FOUNDER',95,485);ctx.font='900 37px Inter,Arial,sans-serif';ctx.fillText('SPECIAL EDITION',98,533);ctx.strokeStyle='#f4c74d';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(95,555);ctx.lineTo(390,555);ctx.stroke();
roundedRect(ctx,105,650,300,300,34);ctx.fillStyle='rgba(12,9,2,.92)';ctx.fill();ctx.lineWidth=9;ctx.strokeStyle='#e0a828';ctx.stroke();ctx.textAlign='center';ctx.fillStyle='#f8cf58';ctx.font='900 49px Inter,Arial,sans-serif';ctx.fillText('FOUNDER',255,735);ctx.fillText('SERIES',255,797);ctx.font='900 52px Inter,Arial,sans-serif';ctx.fillText(`${n} OF 100`,255,875);ctx.font='900 74px Inter,Arial,sans-serif';ctx.fillText('★',255,935);
const labels=[['CONNECT','♟','#a64cff'],['FOLLOW','◈','#84ff00'],['BUILD','◆','#8b2eff'],['SHOW','🏆','#84ff00'],['INSPIRE','🔥','#9f41ff']];ctx.textAlign='left';ctx.font='900 italic 39px Inter,Arial,sans-serif';labels.forEach((item,i)=>{const y=485+i*72;ctx.fillStyle=item[2];ctx.font='900 46px Inter,Arial,sans-serif';ctx.fillText(item[1],1210,y);ctx.fillStyle='#fff';ctx.font='900 italic 39px Inter,Arial,sans-serif';ctx.fillText(item[0],1280,y);});
const qr=await qrCanvas(url,760);roundedRect(ctx,475,420,650,650,36);ctx.fillStyle=metallicGradient(ctx,475,420,1125,1070);ctx.fill();ctx.lineWidth=16;ctx.strokeStyle='#84ff00';ctx.stroke();ctx.drawImage(qr,515,460,570,570);roundedRect(ctx,714,694,172,172,30);ctx.fillStyle='#08090a';ctx.fill();ctx.lineWidth=8;ctx.strokeStyle='#8b2eff';ctx.stroke();ctx.textAlign='center';ctx.font='900 italic 78px Inter,Arial,sans-serif';ctx.fillStyle='#84ff00';ctx.fillText('HF',800,808);
roundedRect(ctx,230,1070,1140,255,32);ctx.fillStyle='rgba(4,5,6,.96)';ctx.fill();ctx.lineWidth=12;ctx.strokeStyle=metallicGradient(ctx,230,1070,1370,1325);ctx.stroke();ctx.textAlign='center';ctx.fillStyle=metallicGradient(ctx,280,1100,1320,1270);ctx.font=`900 ${fitText(ctx,vehicle.hotflash_id||'HF-000000',960,115,64)}px Inter,Arial,sans-serif`;ctx.fillText(vehicle.hotflash_id||'HF-000000',800,1200);ctx.fillStyle='#84ff00';ctx.font=`900 italic ${fitText(ctx,owner,960,66,38)}px Inter,Arial,sans-serif`;ctx.fillText(owner,800,1270);ctx.fillStyle='#9d45ff';ctx.font=`900 italic ${fitText(ctx,nickname,760,60,34)}px Inter,Arial,sans-serif`;ctx.fillText(nickname,800,1330);
ctx.fillStyle='#f4c74d';ctx.font='900 30px Inter,Arial,sans-serif';ctx.textAlign='left';ctx.fillText('EST. 2026',250,1432);ctx.textAlign='right';ctx.fillText('ALPHA MEMBER',1350,1432);ctx.textAlign='center';ctx.fillStyle='#ad64ff';ctx.font='900 38px Inter,Arial,sans-serif';ctx.fillText('★  FOUNDER  ★',800,1452);ctx.fillStyle='#84ff00';ctx.font='900 28px Inter,Arial,sans-serif';ctx.fillText('HOTFLASH.APP',800,1502);ctx.fillStyle='rgba(255,255,255,.76)';ctx.font='700 24px Inter,Arial,sans-serif';ctx.fillText(handle,800,1540);return c;}
async function buildStandardSticker(vehicle){const S=1200,c=document.createElement('canvas'),ctx=c.getContext('2d');c.width=c.height=S;const url=canonicalVehicleUrl(vehicle);ctx.fillStyle='#050607';ctx.fillRect(0,0,S,S);const g=ctx.createRadialGradient(600,380,40,600,600,800);g.addColorStop(0,'#221038');g.addColorStop(.55,'#080a0c');g.addColorStop(1,'#020303');ctx.fillStyle=g;ctx.fillRect(0,0,S,S);ctx.lineWidth=18;ctx.strokeStyle=neonGradient(ctx,40,40,1160,1160);ctx.strokeRect(35,35,1130,1130);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='900 italic 98px Inter,Arial,sans-serif';ctx.fillText('HOT FLASH',600,150);ctx.fillStyle='#84ff00';ctx.font='900 38px Inter,Arial,sans-serif';ctx.fillText(vehicle.hotflash_id||'VEHICLE FLASHTAG',600,215);const qr=await qrCanvas(url,760);ctx.fillStyle='#fff';ctx.fillRect(210,260,780,780);ctx.drawImage(qr,250,300,700,700);ctx.fillStyle='#fff';ctx.font=`900 ${fitText(ctx,vehicle.nickname||'Hot Flash Build',940,70,38)}px Inter,Arial,sans-serif`;ctx.fillText(vehicle.nickname||'Hot Flash Build',600,1090);ctx.fillStyle='#84ff00';ctx.font='800 28px Inter,Arial,sans-serif';ctx.fillText('SCAN THE BUILD • HOTFLASH.APP',600,1140);return c;}
async function buildCompleteSticker(vehicle,profile){return founderNumber(vehicle)?buildFounderSticker(vehicle,profile):buildStandardSticker(vehicle);}
function downloadCanvas(canvas,filename){canvas.toBlob(blob=>{if(!blob)return;const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1500);},'image/png');}
async function downloadCompleteSticker(vehicle,profile,status){try{if(status)status.textContent='Rendering full sticker…';const canvas=await buildCompleteSticker(vehicle,profile);downloadCanvas(canvas,flashTagFilename(vehicle,Boolean(founderNumber(vehicle))));if(status)status.textContent='Full sticker downloaded.';}catch(error){if(status)status.textContent=error.message||'Sticker could not be rendered.';}}
async function shareVehicle(vehicle,url,status){try{if(navigator.share){await navigator.share({title:`${vehicle.nickname} on Hot Flash`,text:`Check out ${vehicle.nickname} on Hot Flash.`,url});if(status)status.textContent='Shared.';}else{await navigator.clipboard.writeText(url);if(status)status.textContent='Link copied.';}}catch(error){if(error.name!=='AbortError'&&status)status.textContent='Could not share this link.';}}
window.renderFlashTag=function(vehicle,profile={}){const card=document.querySelector('[data-flashtag-card]'),qr=document.querySelector('[data-flashtag-qr]');if(!card||!qr||!vehicle)return;const url=canonicalVehicleUrl(vehicle),id=vehicle.hotflash_id||'Hot Flash vehicle',isFounder=Boolean(founderNumber(vehicle)),status=document.querySelector('[data-flashtag-status]');card.hidden=false;card.classList.toggle('founder-flashtag',isFounder);document.querySelector('[data-flashtag-id]').textContent=id;document.querySelector('[data-flashtag-name]').textContent=vehicle.nickname||'Vehicle FlashTag';document.querySelector('[data-flashtag-url]').textContent=url;buildQr(qr,url,280);const download=document.querySelector('[data-flashtag-download]');if(download){download.textContent=isFounder?'Download Full Founder Sticker':'Download Full FlashTag';download.onclick=()=>downloadCompleteSticker(vehicle,profile,status);}document.querySelector('[data-flashtag-copy]')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(url);status.textContent='Link copied.';});document.querySelector('[data-flashtag-share]')?.addEventListener('click',()=>shareVehicle(vehicle,url,status));const printLink=document.querySelector('[data-flashtag-print]');if(printLink)printLink.href=`flashtag.html?hf=${encodeURIComponent(id)}`;};
async function findVehicle(ref){let query=hotflashSupabase.from('vehicles').select('*');query=ref.startsWith('HF-')?query.eq('hotflash_id',ref):query.eq('id',ref);return query.maybeSingle();}
async function findOwner(vehicle){if(!vehicle?.owner_id)return {};const{data}=await hotflashSupabase.from('profiles').select('username,display_name,avatar_url,founder_number').eq('id',vehicle.owner_id).maybeSingle();return data||{};}
async function loadVehicleFlashTag(){if(document.body.dataset.page!=='vehicle')return;const params=new URLSearchParams(location.search),ref=params.get('hf')||params.get('id');if(!ref)return;const{data:vehicle}=await findVehicle(ref);if(vehicle)window.renderFlashTag(vehicle,await findOwner(vehicle));}
async function loadPrintableFlashTag(){if(document.body.dataset.page!=='flashtag')return;const ref=new URLSearchParams(location.search).get('hf'),status=document.querySelector('[data-print-status]');if(!ref){status.textContent='No vehicle selected.';return;}const{data:vehicle,error}=await findVehicle(ref);if(error||!vehicle){status.textContent=error?.message||'Vehicle not found.';return;}const profile=await findOwner(vehicle),url=canonicalVehicleUrl(vehicle),isFounder=Boolean(founderNumber(vehicle));document.title=`${vehicle.nickname} FlashTag | Hot Flash`;document.querySelector('[data-print-id]').textContent=vehicle.hotflash_id||'Hot Flash';document.querySelector('[data-print-name]').textContent=vehicle.nickname;document.querySelector('[data-print-meta]').textContent=[vehicle.year,vehicle.make,vehicle.model].filter(Boolean).join(' ');document.querySelector('[data-print-url]').textContent=url;const qr=document.querySelector('[data-print-qr]');buildQr(qr,url,360);const preview=document.querySelector('[data-sticker-preview]');if(preview){status.textContent='Rendering sticker preview…';const canvas=await buildCompleteSticker(vehicle,profile);preview.innerHTML='';preview.appendChild(canvas);document.querySelector('[data-print-download]').onclick=()=>downloadCanvas(canvas,flashTagFilename(vehicle,isFounder));document.querySelector('[data-print-button]').onclick=()=>window.print();}status.textContent=isFounder?`Founder Special Edition ${founderNumber(vehicle)} of 100`:'FlashTag ready.';}
document.addEventListener('DOMContentLoaded',()=>{loadVehicleFlashTag();loadPrintableFlashTag();});