const $=s=>document.querySelector(s),feed=$('[data-hoon-feed]'),composer=$('[data-hoon-composer]'),form=$('[data-hoon-form]'),statusEl=$('[data-hoon-status]'),feedStatus=$('[data-hoon-feed-status]'),vehicleSelect=$('[data-hoon-vehicle]'),moreButton=$('[data-hoon-more]'),tagPanel=$('[data-hoon-tag-requests]'),tagList=$('[data-hoon-tag-request-list]'),commentsModal=$('[data-hoon-comments-modal]'),commentsList=$('[data-hoon-comments-list]'),commentForm=$('[data-hoon-comment-form]'),commentStatus=$('[data-hoon-comment-status]');
let session=null,posting=false,offset=0,mode='newest',activeCommentPost=null,busy=new Set;const PAGE=12,MAX_VIDEO=100*1024*1024;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const safeUrl=v=>{try{const u=new URL(String(v||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}};
const labels={track:'Track',drift_event:'Drift event',drag_strip:'Drag strip',private_property:'Private property',off_road_park:'Off-road park',closed_course:'Closed course'};
async function getSession(){return window.hotFlashGetStableSession?window.hotFlashGetStableSession():(await hotflashSupabase.auth.getSession()).data.session}
function setStatus(message,type=''){if(statusEl){statusEl.textContent=message;statusEl.className=`small-muted${type?` ${type}`:''}`}}
function dateText(v){const d=new Date(v);return Number.isNaN(d.valueOf())?'':d.toLocaleString([],{dateStyle:'medium',timeStyle:'short'})}
function vehicleName(v){return v?.nickname||[v?.year,v?.make,v?.model].filter(Boolean).join(' ')||v?.hotflash_id||'Vehicle'}
async function requireSession(){session=await getSession();if(!session){location.href=`login.html?returnTo=${encodeURIComponent(location.pathname+location.search)}`;return null}return session}
async function authorInfo(ids){ids=[...new Set(ids.filter(Boolean))];if(!ids.length)return new Map;const{data}=await hotflashSupabase.from('profiles').select('id,username,display_name').in('id',ids);return new Map((data||[]).map(p=>[p.id,p]))}
async function mineMap(table,ids){const map=new Set;if(!session||!ids.length)return map;const{data}=await hotflashSupabase.from(table).select('post_id').eq('user_id',session.user.id).in('post_id',ids);for(const row of data||[])map.add(row.post_id);return map}
async function followingIds(){if(!session)return[];const{data}=await hotflashSupabase.from('profile_followers').select('profile_id').eq('follower_id',session.user.id);return (data||[]).map(x=>x.profile_id)}
async function savedIds(){if(!session)return[];const{data}=await hotflashSupabase.from('hoon_saves').select('post_id').eq('user_id',session.user.id).order('created_at',{ascending:false});return (data||[]).map(x=>x.post_id)}
async function loadFeed(reset=false){if(reset){offset=0;feed.innerHTML=''}session=await getSession();if(!offset)feed.innerHTML='<div class="hoon-empty">Loading Hoon Pad…</div>';let q=hotflashSupabase.from('hoon_post_stats').select('*');if(mode==='following'){if(!session)return loginEmpty('Log in to see clips from members you follow.');const ids=await followingIds();if(!ids.length)return empty('Your Following feed is waiting.','Follow a few members and their newest clips will appear here.');q=q.in('author_id',ids).order('created_at',{ascending:false})}else if(mode==='saved'){if(!session)return loginEmpty('Log in to view your saved clips.');const ids=await savedIds();if(!ids.length)return empty('No saved clips yet.','Tap Save on a clip you want to find again.');q=q.in('id',ids).order('created_at',{ascending:false})}else if(mode==='trending')q=q.order('trending_score',{ascending:false}).order('created_at',{ascending:false});else q=q.order('created_at',{ascending:false});
const{data,error}=await q.range(offset,offset+PAGE-1);if(error){console.error(error);feed.innerHTML='<div class="hoon-empty"><strong>Hoon Pad could not load.</strong><p>Please refresh and try again.</p></div>';moreButton.hidden=true;return}const posts=data||[];if(!offset)feed.innerHTML='';if(!posts.length&&!offset)return empty('Nothing here yet.',mode==='trending'?'Fresh clips need a little activity before they trend.':'Be the first to get this feed moving.');const ids=posts.map(p=>p.id),[authors,flamed,saved]=await Promise.all([authorInfo(posts.map(p=>p.author_id)),mineMap('hoon_flames',ids),mineMap('hoon_saves',ids)]);posts.forEach((post,index)=>renderPost(post,authors.get(post.author_id),flamed.has(post.id),saved.has(post.id),offset+index));offset+=posts.length;moreButton.hidden=posts.length<PAGE;feedStatus.textContent=mode==='trending'?'Trending balances Flames, comments, saves, and freshness.':''}
function empty(title,copy){feed.innerHTML=`<div class="hoon-empty"><strong>${esc(title)}</strong><p>${esc(copy)}</p></div>`;moreButton.hidden=true}
function loginEmpty(copy){empty('Sign in required',copy)}
function renderPost(post,author,isFlamed,isSaved,index){if(index>0&&index%6===0){const d=document.createElement('aside');d.className='hoon-divider';d.innerHTML='<strong>Respect the streets.</strong><span>Save the fun for tracks, private property, and legal events.</span>';feed.appendChild(d)}const mine=session?.user?.id===post.author_id,pending=post.vehicle_tag_status==='pending',card=document.createElement('article');card.className='hoon-card';card.dataset.postId=post.id;card.dataset.storagePath=post.storage_path||'';card.innerHTML=`<video class="hoon-video" controls playsinline preload="metadata" src="${esc(safeUrl(post.video_url))}"></video><div class="hoon-copy"><div class="hoon-meta"><span class="hoon-chip">🟢 ${esc(labels[post.venue_type]||'Legal venue')}</span>${post.venue_name?`<span class="hoon-chip">📍 ${esc(post.venue_name)}</span>`:''}${pending&&mine?'<span class="hoon-chip">Vehicle tag pending</span>':''}</div><h2>${esc(post.caption||'Fresh from the Hoon Pad')}</h2><p class="small-muted">${esc(author?.display_name||author?.username||'Hot Flash member')} · ${esc(dateText(post.created_at))}</p><div class="hoon-actions"><button type="button" data-flame>${isFlamed?'🔥 Flamed':'🔥 Flame'} (${post.flame_count||0})</button><button type="button" data-comments>💬 Comments (${post.comment_count||0})</button><button type="button" data-save>${isSaved?'✓ Saved':'🔖 Save'}</button><button type="button" data-share>Share</button>${post.vehicle_id?`<a class="secondary-button" href="vehicle.html?id=${encodeURIComponent(post.vehicle_id)}">View vehicle</a>`:''}${mine?'<button type="button" class="danger" data-delete>Delete</button>':''}</div></div>`;feed.appendChild(card);card.querySelector('[data-flame]').onclick=()=>toggleRecord('hoon_flames',post.id,card.querySelector('[data-flame]'));card.querySelector('[data-save]').onclick=()=>toggleRecord('hoon_saves',post.id,card.querySelector('[data-save]'));card.querySelector('[data-comments]').onclick=()=>openComments(post);card.querySelector('[data-share]').onclick=()=>sharePost(post);card.querySelector('[data-delete]')?.addEventListener('click',()=>deletePost(card,post.id))}
async function toggleRecord(table,postId,button){if(!await requireSession()||busy.has(`${table}:${postId}`))return;const key=`${table}:${postId}`;busy.add(key);button.disabled=true;try{const{data}=await hotflashSupabase.from(table).select('post_id').eq('post_id',postId).eq('user_id',session.user.id).maybeSingle();const result=data?await hotflashSupabase.from(table).delete().eq('post_id',postId).eq('user_id',session.user.id):await hotflashSupabase.from(table).insert({post_id:postId,user_id:session.user.id});if(result.error)throw result.error;await loadFeed(true)}catch(e){alert(e.message||'That action could not be completed.')}finally{busy.delete(key);button.disabled=false}}
async function sharePost(post){const url=`${location.origin}${location.pathname}?clip=${encodeURIComponent(post.id)}`;try{if(navigator.share)await navigator.share({title:'Hoon Pad clip',text:post.caption||'Check out this Hoon Pad clip.',url});else{await navigator.clipboard.writeText(url);feedStatus.textContent='Clip link copied.'}}catch(e){if(e.name!=='AbortError')feedStatus.textContent='Could not share this clip.'}}
async function openComments(post){activeCommentPost=post;commentsModal.hidden=false;document.body.classList.add('lightbox-open');$('[data-hoon-comments-title]').textContent=post.caption||'Hoon Pad clip';await loadComments()}
async function loadComments(){commentsList.innerHTML='<p class="small-muted">Loading comments…</p>';const{data,error}=await hotflashSupabase.from('hoon_comments').select('id,author_id,body,created_at').eq('post_id',activeCommentPost.id).order('created_at');if(error){commentsList.innerHTML='<p class="error">Comments could not load.</p>';return}const authors=await authorInfo((data||[]).map(x=>x.author_id));commentsList.innerHTML=(data||[]).map(c=>`<article class="hoon-comment"><div><strong>${esc(authors.get(c.author_id)?.display_name||authors.get(c.author_id)?.username||'Member')}</strong><span>${esc(dateText(c.created_at))}</span></div><p>${esc(c.body)}</p>${session?.user?.id===c.author_id?`<button type="button" data-delete-comment="${esc(c.id)}">Delete</button>`:''}</article>`).join('')||'<p class="small-muted">No comments yet. Keep it respectful and start the conversation.</p>';commentsList.querySelectorAll('[data-delete-comment]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this comment?'))return;b.disabled=true;const{error}=await hotflashSupabase.from('hoon_comments').delete().eq('id',b.dataset.deleteComment);if(error){b.disabled=false;return}await loadComments()})}
commentForm?.addEventListener('submit',async e=>{e.preventDefault();if(!await requireSession()||!activeCommentPost)return;const button=commentForm.querySelector('button'),body=String(new FormData(commentForm).get('body')||'').trim();if(!body)return;button.disabled=true;commentStatus.textContent='Posting…';const{error}=await hotflashSupabase.from('hoon_comments').insert({post_id:activeCommentPost.id,author_id:session.user.id,body});if(error)commentStatus.textContent=error.message||'Comment could not be posted.';else{commentForm.reset();commentStatus.textContent='Comment posted.';await loadComments()}button.disabled=false});
$('[data-hoon-comments-close]')?.addEventListener('click',()=>{commentsModal.hidden=true;document.body.classList.remove('lightbox-open');activeCommentPost=null});commentsModal?.addEventListener('click',e=>{if(e.target===commentsModal)$('[data-hoon-comments-close]').click()});
async function loadVehicles(){session=await getSession();if(!session)return;const{data}=await hotflashSupabase.from('vehicles').select('id,hotflash_id,nickname,year,make,model').eq('owner_id',session.user.id).order('created_at',{ascending:false});vehicleSelect.innerHTML='<option value="">Not linked to one of my vehicles</option>'+((data||[]).map(v=>`<option value="${esc(v.hotflash_id||v.id)}">${esc(vehicleName(v))}</option>`).join(''))}
async function openComposer(){if(!await requireSession())return;composer.hidden=false;await loadVehicles();composer.scrollIntoView({behavior:'smooth',block:'start'})}
$('[data-open-hoon-composer]')?.addEventListener('click',openComposer);$('[data-close-hoon-composer]')?.addEventListener('click',()=>{composer.hidden=true;setStatus('')});
async function loadTagRequests(){session=await getSession();if(!session||!tagPanel||!tagList)return;const{data:owned}=await hotflashSupabase.from('vehicles').select('id,hotflash_id,nickname,year,make,model').eq('owner_id',session.user.id),ids=(owned||[]).map(v=>v.id);if(!ids.length){tagPanel.hidden=true;return}const{data}=await hotflashSupabase.from('hoon_posts').select('id,author_id,caption,video_url,requested_vehicle_id').in('requested_vehicle_id',ids).eq('vehicle_tag_status','pending');if(!data?.length){tagPanel.hidden=true;return}const authors=await authorInfo(data.map(x=>x.author_id)),vehicles=new Map((owned||[]).map(v=>[v.id,v]));tagList.innerHTML=data.map(p=>`<article class="hoon-tag-request" data-tag-request="${esc(p.id)}"><video controls playsinline preload="metadata" src="${esc(safeUrl(p.video_url))}"></video><div><strong>${esc(p.caption||'Hoon Pad clip')}</strong><p class="small-muted">${esc(authors.get(p.author_id)?.display_name||authors.get(p.author_id)?.username||'Member')} tagged ${esc(vehicleName(vehicles.get(p.requested_vehicle_id)))}</p><div class="inline-actions"><button data-tag-accept>Accept tag</button><button class="secondary-button" data-tag-decline>Decline</button></div></div></article>`).join('');tagPanel.hidden=false;tagList.querySelectorAll('[data-tag-request]').forEach(card=>card.onclick=async e=>{const accept=e.target.closest('[data-tag-accept]'),decline=e.target.closest('[data-tag-decline]');if(!accept&&!decline)return;const b=accept||decline;b.disabled=true;const{error}=await hotflashSupabase.rpc('respond_to_hoon_vehicle_tag',{p_post_id:card.dataset.tagRequest,p_accept:Boolean(accept)});if(error){b.disabled=false;return}await Promise.all([loadTagRequests(),loadFeed(true)])})}
async function deletePost(card,id){if(!confirm('Delete this Hoon Pad clip? This cannot be undone.'))return;const typed=prompt('Type DELETE to permanently remove the clip.');if(typed!=='DELETE')return;const button=card.querySelector('[data-delete]');button.disabled=true;if(!await requireSession()){button.disabled=false;return}const{data,error}=await hotflashSupabase.from('hoon_posts').delete().eq('id',id).eq('author_id',session.user.id).select('id').maybeSingle();if(error||!data){button.disabled=false;alert(error?.message||'Only the uploader can delete this clip.');return}if(card.dataset.storagePath)await hotflashSupabase.storage.from('hoon-videos').remove([card.dataset.storagePath]);card.remove()}
form?.addEventListener('submit',async e=>{e.preventDefault();if(posting||!await requireSession())return;const fd=new FormData(form),file=fd.get('video'),button=form.querySelector('button[type="submit"]'),ownRef=String(fd.get('vehicle_id')||'').trim(),otherRef=String(fd.get('vehicle_ref')||'').trim();if(ownRef&&otherRef)return setStatus('Choose your vehicle or tag another vehicle, not both.','error');if(!file?.size)return setStatus('Choose a video first.','error');const ext=(file.name.split('.').pop()||'').toLowerCase(),type=file.type||({mp4:'video/mp4',mov:'video/quicktime',webm:'video/webm'}[ext]||'');if(!['video/mp4','video/quicktime','video/webm'].includes(type))return setStatus('Choose an MP4, MOV, or WebM video.','error');if(file.size>MAX_VIDEO)return setStatus('Videos must be 100 MB or smaller.','error');if(fd.get('legal_attestation')!=='on')return setStatus('Confirm the clip was recorded in a safe and legal environment.','error');posting=true;button.disabled=true;button.textContent='Uploading…';const path=`${session.user.id}/${crypto.randomUUID?.()||Date.now()}.${ext||'mp4'}`;try{setStatus('Uploading clip… Keep this page open.');const{error:up}=await hotflashSupabase.storage.from('hoon-videos').upload(path,file,{cacheControl:'3600',upsert:false,contentType:type});if(up)throw up;const url=hotflashSupabase.storage.from('hoon-videos').getPublicUrl(path).data.publicUrl,{error}=await hotflashSupabase.rpc('create_hoon_post',{p_video_url:url,p_storage_path:path,p_caption:String(fd.get('caption')||''),p_venue_type:String(fd.get('venue_type')),p_venue_name:String(fd.get('venue_name')||''),p_vehicle_ref:ownRef||otherRef||null,p_save_to_build_history:fd.get('save_to_build_history')==='on'});if(error){await hotflashSupabase.storage.from('hoon-videos').remove([path]);throw error}form.reset();composer.hidden=true;setStatus(otherRef?'Posted. The vehicle owner must approve the tag.':'Posted to Hoon Pad.','success');mode='newest';syncTabs();await Promise.all([loadFeed(true),loadTagRequests()])}catch(error){setStatus(error.message||'The clip could not be posted.','error')}finally{posting=false;button.disabled=false;button.textContent='Post to Hoon Pad'}});
function syncTabs(){document.querySelectorAll('[data-hoon-feed-mode]').forEach(b=>b.classList.toggle('active',b.dataset.hoonFeedMode===mode))}
document.querySelectorAll('[data-hoon-feed-mode]').forEach(b=>b.onclick=async()=>{mode=b.dataset.hoonFeedMode;syncTabs();await loadFeed(true)});moreButton?.addEventListener('click',()=>loadFeed(false));
document.addEventListener('DOMContentLoaded',async()=>{const clip=new URLSearchParams(location.search).get('clip');await Promise.all([loadFeed(true),loadTagRequests()]);if(location.hash==='#create')openComposer();if(clip)setTimeout(()=>document.querySelector(`[data-post-id="${CSS.escape(clip)}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),400)});