-- Hot Flash FlashTag fulfillment queue
-- Safe to rerun in Supabase SQL Editor after supabase-admin-console.sql.

create table if not exists public.flashtag_orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  vehicle_id uuid references public.vehicles(id) on delete restrict,
  customer_user_id uuid references auth.users(id) on delete set null,
  customer_name text,
  customer_email text,
  quantity integer not null default 1,
  shipping_name text,
  address_line_1 text,
  address_line_2 text,
  city text,
  state_region text,
  postal_code text,
  country text not null default 'United States',
  notes text,
  status text not null default 'new',
  tracking_number text,
  carrier text,
  ordered_at timestamptz not null default now(),
  printed_at timestamptz,
  shipped_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

alter table public.flashtag_orders
  add column if not exists order_number bigint generated by default as identity,
  add column if not exists vehicle_id uuid references public.vehicles(id) on delete restrict,
  add column if not exists customer_user_id uuid references auth.users(id) on delete set null,
  add column if not exists customer_name text,
  add column if not exists customer_email text,
  add column if not exists quantity integer not null default 1,
  add column if not exists shipping_name text,
  add column if not exists address_line_1 text,
  add column if not exists address_line_2 text,
  add column if not exists city text,
  add column if not exists state_region text,
  add column if not exists postal_code text,
  add column if not exists country text not null default 'United States',
  add column if not exists notes text,
  add column if not exists status text not null default 'new',
  add column if not exists tracking_number text,
  add column if not exists carrier text,
  add column if not exists ordered_at timestamptz not null default now(),
  add column if not exists printed_at timestamptz,
  add column if not exists shipped_at timestamptz,
  add column if not exists completed_at timestamptz,
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists updated_by uuid references auth.users(id) on delete set null;

update public.flashtag_orders set quantity=1 where quantity is null;
update public.flashtag_orders set country='United States' where country is null or trim(country)='';
update public.flashtag_orders set status='new' where status is null or status not in ('new','printing','printed','shipped','completed','cancelled');
update public.flashtag_orders set ordered_at=now() where ordered_at is null;
update public.flashtag_orders set updated_at=coalesce(updated_at,ordered_at,now()) where updated_at is null;

do $$
begin
  if not exists(select 1 from pg_constraint where conname='flashtag_orders_order_number_key') then
    alter table public.flashtag_orders add constraint flashtag_orders_order_number_key unique(order_number);
  end if;
  if not exists(select 1 from pg_constraint where conname='flashtag_orders_quantity_check') then
    alter table public.flashtag_orders add constraint flashtag_orders_quantity_check check (quantity between 1 and 100);
  end if;
  if not exists(select 1 from pg_constraint where conname='flashtag_orders_status_check') then
    alter table public.flashtag_orders add constraint flashtag_orders_status_check check (status in ('new','printing','printed','shipped','completed','cancelled'));
  end if;
end $$;

create index if not exists flashtag_orders_status_idx on public.flashtag_orders(status,ordered_at desc);
create index if not exists flashtag_orders_vehicle_idx on public.flashtag_orders(vehicle_id);

alter table public.flashtag_orders enable row level security;

drop policy if exists "Customers can view own FlashTag orders" on public.flashtag_orders;
create policy "Customers can view own FlashTag orders"
on public.flashtag_orders for select
to authenticated
using (customer_user_id = auth.uid());

create or replace function public.admin_list_flashtag_orders(p_status text default null)
returns table (
  id uuid,
  order_number bigint,
  vehicle_id uuid,
  hotflash_id text,
  nickname text,
  year integer,
  make text,
  model text,
  customer_name text,
  customer_email text,
  quantity integer,
  shipping_name text,
  address_line_1 text,
  address_line_2 text,
  city text,
  state_region text,
  postal_code text,
  country text,
  notes text,
  status text,
  tracking_number text,
  carrier text,
  ordered_at timestamptz,
  printed_at timestamptz,
  shipped_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_hotflash_admin() then
    raise exception 'FlashTag fulfillment access required';
  end if;
  return query
  select o.id,o.order_number,o.vehicle_id,v.hotflash_id,v.nickname,v.year,v.make,v.model,
         o.customer_name,o.customer_email,o.quantity,o.shipping_name,o.address_line_1,o.address_line_2,
         o.city,o.state_region,o.postal_code,o.country,o.notes,o.status,o.tracking_number,o.carrier,
         o.ordered_at,o.printed_at,o.shipped_at
  from public.flashtag_orders o
  join public.vehicles v on v.id=o.vehicle_id
  where p_status is null or o.status=p_status
  order by case o.status when 'new' then 0 when 'printing' then 1 when 'printed' then 2 when 'shipped' then 3 else 4 end,
           o.ordered_at asc;
end;
$$;

create or replace function public.admin_update_flashtag_order(
  p_order_id uuid,
  p_status text,
  p_tracking_number text default null,
  p_carrier text default null
)
returns public.flashtag_orders
language plpgsql
security definer
set search_path = public
as $$
declare v_order public.flashtag_orders;
begin
  if not public.is_hotflash_admin() then
    raise exception 'FlashTag fulfillment access required';
  end if;
  if p_status not in ('new','printing','printed','shipped','completed','cancelled') then
    raise exception 'Invalid order status';
  end if;
  update public.flashtag_orders set
    status=p_status,
    tracking_number=nullif(trim(p_tracking_number),''),
    carrier=nullif(trim(p_carrier),''),
    printed_at=case when p_status in ('printed','shipped','completed') then coalesce(printed_at,now()) else printed_at end,
    shipped_at=case when p_status in ('shipped','completed') then coalesce(shipped_at,now()) else shipped_at end,
    completed_at=case when p_status='completed' then coalesce(completed_at,now()) else completed_at end,
    updated_at=now(),updated_by=auth.uid()
  where id=p_order_id
  returning * into v_order;
  if v_order.id is null then raise exception 'Order not found'; end if;
  return v_order;
end;
$$;

grant execute on function public.admin_list_flashtag_orders(text) to authenticated;
grant execute on function public.admin_update_flashtag_order(uuid,text,text,text) to authenticated;

comment on table public.flashtag_orders is 'Physical FlashTag orders linked to the vehicle permanent identity. Artwork is always rendered from the vehicle hotflash_id.';