(()=>{
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function session(){return window.hotFlashGetStableSession?window.hotFlashGetStableSession():(await hotflashSupabase.auth.getSession()).data.session}
 async function state(type,id){const{data,error}=await hotflashSupabase.rpc('get_hotflash_follow_state',{p_subject_type:type,p_subject_id:id});if(error)throw error;return data||{following:false,count:0}}
 function label(type){return type==='shop'?'shop':type==='event'?'event':type==='member'?'member':'vehicle'}
 async function mount(root,type,id,ownerId){if(!root||!id||root.dataset.followReady)return;root.dataset.followReady='1';const s=await session();if(s?.user?.id===ownerId)return;const wrap=document.createElement('div');wrap.className='hf-follow-control';wrap.innerHTML=`<button type="button" data-hf-follow>Follow ${esc(label(type))}</button><span class="small-muted" data-hf-follow-count></span>`;root.appendChild(wrap);const button=wrap.querySelector('[data-hf-follow]'),count=wrap.querySelector('[data-hf-follow-count]');let current=await state(type,id);const render=()=>{button.textContent=current.following?`Following ${label(type)} ✓`:`Follow ${label(type)}`;button.classList.toggle('following',!!current.following);button.setAttribute('aria-pressed',String(!!current.following));count.textContent=`${Number(current.count||0)} follower${Number(current.count||0)===1?'':'s'}`};render();button.onclick=async()=>{const auth=await session();if(!auth){location.href=`login.html?returnTo=${encodeURIComponent(location.pathname+location.search)}`;return}button.disabled=true;button.textContent='Saving…';const{data,error}=await hotflashSupabase.rpc('toggle_hotflash_follow',{p_subject_type:type,p_subject_id:id});button.disabled=false;if(error){button.textContent='Try again';count.textContent=error.message||'Could not update follow.';return}current=data;render()}}
 async function shop(){const slug=new URLSearchParams(location.search).get('s'),idParam=new URLSearchParams(location.search).get('id');if(!slug&&!idParam)return;let q=hotflashSupabase.from('shops').select('id');q=slug?q.eq('slug',slug):q.eq('id',idParam);const{data}=await q.maybeSingle();if(!data)return;let owner=null;const{data:member}=await hotflashSupabase.from('shop_members').select('user_id').eq('shop_id',data.id).eq('role','owner').eq('status','active').limit(1).maybeSingle();owner=member?.user_id||null;const root=document.querySelector('[data-shop-contact]')||document.querySelector('[data-shop-profile]');await mount(root,'shop',data.id,owner)}
 async function eventPage(){const id=new URLSearchParams(location.search).get('id');if(!id)return;const root=document.querySelector('[data-event-actions]')||document.querySelector('[data-event-card]')||document.querySelector('main');if(root)await mount(root,'event',id,null)}
 document.addEventListener('DOMContentLoaded',()=>{const page=document.body?.dataset?.page||location.pathname.split('/').pop();if(page==='shop'||String(page).includes('shop'))shop().catch(console.warn);if(page==='event'||String(page).includes('event'))eventPage().catch(console.warn)});
 window.HotFlashFollow={mount};
})();
